---
# Configure kubeconfig file for 'admin'

- name: Get k8s' CA certificate
  command: bash -c "base64 {{ k8s_cert_location }}/ca.pem | tr -d '\n'"
  register: k8s_ca

- name: Get k8s admin's certificate
  command: bash -c "base64 {{ k8s_cert_location }}/admin.pem | tr -d '\n'"
  register: admin_cert

- name: Get k8s admin's key
  command: bash -c "base64 {{ k8s_cert_location }}/admin-key.pem | tr -d '\n'"
  register: admin_key

- name: Make admin's kubeconfig
  template: src=k8s/admin.kubeconfig.j2 dest={{ ansible_env.HOME }}/admin.kubeconfig mode=0644
