---
# Configure passwordless SSH from 'admin' to 'all'

- name: Generate SSH key
  command: 'ssh-keygen -t rsa -N "" -f {{ ansible_env.HOME }}/.ssh/id_rsa'
  ignore_errors: yes
  when: ansible_connection != 'local'

- name: Get SSH public key
  command: "cat {{ ansible_env.HOME }}/.ssh/id_rsa.pub"
  register: ssh_pubkey

- name: Configure passwordless SSH
  authorized_key: user=root key={{ ssh_pubkey.stdout }}
  delegate_to: "{{ item }}"
  become: yes
  when: item != groups.admin.0
  with_items: "{{ groups['all'] }}"

- name: Scan public key
  command: "ssh-keyscan -t rsa {{ item }}"
  register: ssh_keyscan
  when: item != groups.admin.0
  with_items: "{{ groups['all'] }}"

- name: Add hosts to known_hosts file
  known_hosts: name={{ item.item }} path="{{ ansible_env.HOME }}/.ssh/known_hosts" key={{ item.stdout }} state=present
  when: item.item != groups.admin.0
  with_items: "{{ ssh_keyscan.results }}"
